-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM (SELECT *
      FROM ANIMAL_INS
      WHERE SEX_UPON_INTAKE LIKE "Intact%") I
JOIN (SELECT *
      FROM ANIMAL_OUTS
      WHERE SEX_UPON_OUTCOME LIKE "Spayed%"OR SEX_UPON_OUTCOME LIKE "Neutered%") O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY I.ANIMAL_ID ASC