-- 코드를 입력하세요
SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U
JOIN (SELECT USER_ID,YEAR(SALES_DATE)AS YEAR, MONTH(SALES_DATE) AS MONTH
      FROM ONLINE_SALE
     ) O
ON U.USER_ID = O.USER_ID
GROUP BY O.YEAR , O.MONTH , U.GENDER 
HAVING U.GENDER IS NOT NULL
ORDER BY O.YEAR, O.MONTH, U.GENDER
