SELECT  
CASE WHEN SUBSTRING(DIFFERENTIATION_DATE,6,2)=01
    OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=02 
    OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=03 THEN '1Q' 
        WHEN SUBSTRING(DIFFERENTIATION_DATE,6,2)=04
        OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=05 
        OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=06 THEN '2Q' 
WHEN SUBSTRING(DIFFERENTIATION_DATE,6,2)=07
OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=08 
OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=09 THEN '3Q' 
    WHEN SUBSTRING(DIFFERENTIATION_DATE,6,2)=10 
    OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=11 
    OR SUBSTRING(DIFFERENTIATION_DATE,6,2)=12 THEN '4Q'
END AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER

