-- 코드를 입력하세요
SELECT CAR_ID
FROM (SELECT A.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
WHERE A.CAR_TYPE='세단' AND MONTH(B.START_DATE) = 10) M
GROUP BY CAR_ID
ORDER BY CAR_ID DESC