-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES 
FROM BOOK, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# YEAR(BOOK.PUBLISHED_DATE) = 2022
#   AND MONTH(BOOK.PUBLISHED_DATE) = 1
GROUP BY BOOK.CATEGORY 
ORDER BY BOOK.CATEGORY;